[package]
name = "ecs"
version = "0.1.0"
authors = ["Angel Landoni <angel.landoni.usa@gmail.com>"]
edition = "2018"

[dependencies]
fxhash = "0.2.1"
guard = "0.5.1"
tasks = { path="../tasks" }
utils = { path="../utils" }